name: CI

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    lint-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "latest"

            - name: Install dependencies
              run: bun install

            - name: Lint code
              run: bun run lint

            - name: Unit & Integration tests
              run: bun run test

            - name: Smoke & Acceptance tests
              run: |
                  pnpm run build-storybook --quiet
                  pnpm playwright install
                  pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "pnpm dlx http-server storybook-static --port 6006 --silent" \
                    "pnpm dlx wait-on tcp:127.0.0.1:6006 && pnpm run test-storybook"

            - name: Build app
              run: bun run build
